# =============================================================
# FAIL2BAN — Filtro para SFTPGo (logs de autenticación)
# =============================================================
[INCLUDES]
before = common.conf

[Definition]
failregex = .*"level":"warn".*"sender":"sftpd".*"client_ip":"<HOST>".*"error":"authentication failed".*
            .*"level":"error".*"sender":"sftpd".*"client_ip":"<HOST>".*"error":"no matching.*algorithm".*
ignoreregex =
